name: Android CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

jobs:
  build:
    name: Development build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Access SERVER_URL
        env:
          SERVER_URL: $
        run: echo '${{ secrets.SERVER_URL }}' > ./apikey.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check Lint
        run: ./gradlew ktlintCheck

  ui-test:
    name: UI tests on Android (API level ${{ matrix.api-level }})
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 23, 30, 31 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Access SERVER_URL
        env:
          SERVER_URL: $
        run: echo '${{ secrets.SERVER_URL }}' > ./apikey.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run UI test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          arch: x86_64
          script: ./gradlew connectedCheck
